'use client';

import { useEffect, useState } from 'react';
import { CalendarClock, CheckCircle2, Copy, LoaderCircle, ShieldCheck, UserPlus, Users, X } from 'lucide-react';

const DAYS=[{dayOfWeek:1,label:'Senin'},{dayOfWeek:2,label:'Selasa'},{dayOfWeek:3,label:'Rabu'},{dayOfWeek:4,label:'Kamis'},{dayOfWeek:5,label:'Jumat'},{dayOfWeek:6,label:'Sabtu'},{dayOfWeek:0,label:'Minggu'}];
const defaultHours=DAYS.map(day=>({...day,isOpen:day.dayOfWeek>=1&&day.dayOfWeek<=6,openTime:'08:00',closeTime:day.dayOfWeek===6?'13:00':'17:00'}));

export default function UsersPage(){
  const [users,setUsers]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const [showInvite,setShowInvite]=useState(false),[inviteUrl,setInviteUrl]=useState('');
  const [invite,setInvite]=useState({fullName:'',email:'',phone:'',role:'branch_admin',branchId:''});
  const [branchId,setBranchId]=useState(''),[hours,setHours]=useState<any[]>(defaultHours),[openOnHolidays,setOpenOnHolidays]=useState(false);

  const loadUsers=async()=>{setLoading(true);setError('');try{const result=await fetch('/api/users',{cache:'no-store'}).then(r=>r.json());if(!result.success)throw new Error(result.error);setUsers(result.data.users||[]);setBranches(result.data.branches||[]);setBranchId(current=>current||result.data.branches?.[0]?.id||'');setInvite(current=>({...current,branchId:current.branchId||result.data.branches?.[0]?.id||''}));}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{loadUsers()},[]);
  useEffect(()=>{if(!branchId)return;fetch(`/api/branch-schedules?branchId=${encodeURIComponent(branchId)}`,{cache:'no-store'}).then(r=>r.json()).then(result=>{if(!result.success)throw new Error(result.error);const rows=DAYS.map(day=>{const saved=result.data.hours.find((item:any)=>item.dayOfWeek===day.dayOfWeek);return {...day,isOpen:Boolean(saved?.isOpen),openTime:saved?.openTime||'08:00',closeTime:saved?.closeTime||'17:00'}});setHours(rows);setOpenOnHolidays(Boolean(result.data.branch.openOnNationalHolidays));}).catch(e=>setError(e.message));},[branchId]);

  const createInvite=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setInviteUrl('');try{const result=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...invite,branchId:invite.role==='branch_admin'?invite.branchId:undefined,channel:'link'})}).then(r=>r.json());if(!result.success)throw new Error(result.error);setInviteUrl(result.data.inviteUrl);setMessage('Undangan berhasil dibuat. Kirim tautan aktivasi kepada user.');}catch(e:any){setError(e.message)}finally{setSaving(false)}};
  const updateUser=async(user:any,updates:any)=>{setError('');try{const result=await fetch('/api/users',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:user.userId,role:user.role,branchId:user.branchId,isActive:user.isActive,...updates})}).then(r=>r.json());if(!result.success)throw new Error(result.error);setMessage('Data user berhasil diperbarui.');loadUsers();}catch(e:any){setError(e.message)}};
  const saveHours=async()=>{setSaving(true);setError('');try{const result=await fetch('/api/branch-schedules',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({branchId,openOnNationalHolidays:openOnHolidays,hours:hours.map(({dayOfWeek,isOpen,openTime,closeTime})=>({dayOfWeek,isOpen,openTime,closeTime}))})}).then(r=>r.json());if(!result.success)throw new Error(result.error);setMessage('Jam operasional cabang berhasil disimpan dan langsung berlaku pada form booking.');}catch(e:any){setError(e.message)}finally{setSaving(false)}};

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-bold text-slate-900">User & Jam Operasional</h1><p className="mt-1 text-xs text-slate-500">Kelola akses user cabang dan batas waktu booking setiap cabang.</p></div><button onClick={()=>setShowInvite(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white shadow-md"><UserPlus className="h-4 w-4"/>Tambah user</button></div>
    {message&&<div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
    {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-blue-600"/><div><h2 className="text-sm font-extrabold">Manajemen user</h2><p className="text-xs text-slate-500">User cabang hanya dapat ditautkan ke satu cabang.</p></div></div>
      {loading?<div className="flex items-center gap-2 py-8 text-sm text-slate-500"><LoaderCircle className="h-4 w-4 animate-spin"/>Memuat user…</div>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="p-3">Nama</th><th className="p-3">Role</th><th className="p-3">Cabang</th><th className="p-3">Status</th></tr></thead><tbody>{users.map(user=><tr key={user.userId} className="border-b border-slate-100"><td className="p-3"><strong className="block text-slate-900">{user.fullName}</strong><span className="text-slate-500">{user.email}</span></td><td className="p-3"><select value={user.role} onChange={e=>updateUser(user,{role:e.target.value,branchId:e.target.value==='branch_admin'?(user.branchId||branches[0]?.id):null})} className="rounded-lg border border-slate-200 px-2 py-1.5"><option value="super_admin">Super admin</option><option value="branch_admin">Admin cabang</option><option value="finance">Finance</option><option value="sales">Sales</option></select></td><td className="p-3">{user.role==='branch_admin'?<select value={user.branchId||''} onChange={e=>updateUser(user,{branchId:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5">{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select>:<span className="text-slate-400">Semua cabang</span>}</td><td className="p-3"><button onClick={()=>updateUser(user,{isActive:!user.isActive})} className={`rounded-full px-3 py-1 font-bold ${user.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{user.isActive?'Aktif':'Nonaktif'}</button></td></tr>)}</tbody></table></div>}
    </section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-emerald-600"/><div><h2 className="text-sm font-extrabold">Hari dan jam operasional</h2><p className="text-xs text-slate-500">Jam tutup adalah batas selesai booking. Jika tutup 13:00, slot 12:00–13:00 tetap dapat dipilih.</p></div></div><label className="text-xs font-bold text-slate-600">Cabang<select value={branchId} onChange={e=>setBranchId(e.target.value)} className="ml-2 rounded-xl border border-slate-200 px-3 py-2">{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label></div>
      <div className="space-y-2">{hours.map((item,index)=><div key={item.dayOfWeek} className="grid items-center gap-3 rounded-xl border border-slate-200 p-3 sm:grid-cols-[110px_90px_1fr_24px_1fr]"><span className="text-sm font-bold">{item.label}</span><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={item.isOpen} onChange={e=>setHours(current=>current.map((row,i)=>i===index?{...row,isOpen:e.target.checked}:row))}/>{item.isOpen?'Buka':'Tutup'}</label><input type="time" step={1800} disabled={!item.isOpen} value={item.openTime} onChange={e=>setHours(current=>current.map((row,i)=>i===index?{...row,openTime:e.target.value}:row))} className="rounded-lg border border-slate-200 px-3 py-2 disabled:bg-slate-100"/><span className="text-center text-slate-400">–</span><input type="time" step={1800} disabled={!item.isOpen} value={item.closeTime} onChange={e=>setHours(current=>current.map((row,i)=>i===index?{...row,closeTime:e.target.value}:row))} className="rounded-lg border border-slate-200 px-3 py-2 disabled:bg-slate-100"/></div>)}</div>
      <label className="mt-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><input type="checkbox" checked={openOnHolidays} onChange={e=>setOpenOnHolidays(e.target.checked)} className="mt-0.5"/><span><strong className="block text-sm text-amber-900">Tetap buka pada libur nasional</strong><span className="text-xs text-amber-700">Jika dimatikan, seluruh slot pada tanggal merah nasional akan ditutup otomatis.</span></span></label>
      <button onClick={saveHours} disabled={saving||!branchId} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-xs font-bold text-white disabled:opacity-50">{saving&&<LoaderCircle className="h-4 w-4 animate-spin"/>}Simpan jam operasional</button>
    </section>

    {showInvite&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={createInvite} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">Tambah user BOffice</h3><p className="text-xs text-slate-500">User membuat password sendiri melalui tautan aktivasi.</p></div><button type="button" onClick={()=>setShowInvite(false)}><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Nama lengkap<input required value={invite.fullName} onChange={e=>setInvite({...invite,fullName:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-xs font-bold">Email<input required type="email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-xs font-bold">Nomor WhatsApp<input value={invite.phone} onChange={e=>setInvite({...invite,phone:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-xs font-bold">Role<select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="branch_admin">Admin cabang</option><option value="finance">Finance</option><option value="sales">Sales</option><option value="super_admin">Super admin</option></select></label>{invite.role==='branch_admin'&&<label className="text-xs font-bold sm:col-span-2">Cabang<select required value={invite.branchId} onChange={e=>setInvite({...invite,branchId:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5">{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label>}</div>{inviteUrl&&<div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3"><p className="text-xs font-bold text-blue-800">Tautan aktivasi (berlaku 24 jam)</p><div className="mt-2 flex gap-2"><input readOnly value={inviteUrl} className="min-w-0 flex-1 rounded-lg border border-blue-200 bg-white px-3 py-2 text-xs"/><button type="button" onClick={()=>navigator.clipboard.writeText(inviteUrl)} className="rounded-lg bg-blue-600 px-3 text-white"><Copy className="h-4 w-4"/></button></div></div>}<button disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white"><ShieldCheck className="h-4 w-4"/>{saving?'Membuat undangan…':'Buat undangan user'}</button></form></div>}
  </div>
}
