'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Landmark, Plus, Printer, Wallet, X } from 'lucide-react';

const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500';

export default function FinancePage(){
 const [payload,setPayload]=useState<any>({transactions:[],branches:[],summary:{income:0,expense:0,net:0,receivable:0}});const [branch,setBranch]=useState('all');const [open,setOpen]=useState(false);const [notice,setNotice]=useState('');
 const now=new Date();const [periodStart,setPeriodStart]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`);const [periodEnd,setPeriodEnd]=useState(now.toISOString().slice(0,10));const [shares,setShares]=useState<any[]>([]);
 const loadShares=async()=>{const out=await fetch(`/api/profit-sharing?start=${periodStart}&end=${periodEnd}`).then(r=>r.json());setShares(out.data||[])};
 const load=async()=>{const out=await fetch(`/api/finance?branchId=${branch}`).then(r=>r.json());setPayload(out.data||payload)};useEffect(()=>{load()},[branch]);useEffect(()=>{loadShares()},[periodStart,periodEnd]);
 const rows=useMemo(()=>payload.transactions||[],[payload]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const raw:any=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(raw)});const out=await res.json();if(!res.ok){setNotice(out.error);return}setOpen(false);setNotice('Transaksi berhasil dicatat.');load()};
 return <div className="space-y-6 print:p-0"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Cash basis</p><h1 className="mt-1 text-2xl font-extrabold">Manajemen Keuangan</h1><p className="mt-1 text-sm text-slate-500">Pemasukan yang sudah diterima, pengeluaran, dan posisi kas per cabang.</p></div><div className="flex gap-2 print:hidden"><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold"><Printer className="h-4 w-4"/>Ekspor PDF</button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Catat transaksi</button></div></div>
 {notice&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800 print:hidden">{notice}</div>}
 <div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 print:hidden"><span className="text-xs font-bold text-slate-500">Cabang</span><select value={branch} onChange={e=>setBranch(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><option value="all">Semua cabang</option>{payload.branches.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
 <div className="grid gap-4 md:grid-cols-4"><Metric icon={ArrowUpRight} label="Pemasukan diterima" value={money(payload.summary.income)} color="emerald"/><Metric icon={ArrowDownRight} label="Pengeluaran" value={money(payload.summary.expense)} color="rose"/><Metric icon={Wallet} label="Arus kas bersih" value={money(payload.summary.net)} color="blue"/><Metric icon={Landmark} label="Piutang invoice" value={money(payload.summary.receivable)} color="amber"/></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-extrabold">Buku kas</h2><p className="text-xs text-slate-500">Pembayaran invoice masuk otomatis; transaksi lain dicatat manual.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-5 py-3">Tanggal</th><th className="px-5 py-3">Cabang</th><th className="px-5 py-3">Kategori</th><th className="px-5 py-3">Keterangan</th><th className="px-5 py-3 text-right">Nilai</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((t:any)=><tr key={t.id}><td className="px-5 py-4">{t.transactionDate}</td><td className="px-5 py-4">{payload.branches.find((b:any)=>b.id===t.branchId)?.name||'-'}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 font-bold">{t.category}</span></td><td className="px-5 py-4"><strong>{t.description}</strong><p className="text-[10px] text-slate-400">{t.sourceType==='invoice_payment'?'Otomatis dari invoice':'Input manual'}</p></td><td className={`px-5 py-4 text-right font-extrabold ${t.direction==='income'?'text-emerald-600':'text-rose-600'}`}>{t.direction==='income'?'+':'−'} {money(t.amount)}</td></tr>)}{!rows.length&&<tr><td colSpan={5} className="p-10 text-center text-slate-400">Belum ada transaksi pada filter ini.</td></tr>}</tbody></table></div></div>
 <section className="rounded-2xl border border-indigo-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-extrabold">Laporan bagi hasil properti</h2><p className="text-xs text-slate-500">Berbasis kas diterima, setelah HPP, komisi, refund, dan operasional.</p></div><div className="flex gap-2 print:hidden"><input type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs"/><input type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs"/></div></div><div className="grid gap-4 p-5 lg:grid-cols-2">{shares.map((s:any)=><div key={s.branchId} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><div><strong>{s.branchName}</strong><p className="text-xs text-slate-400">{s.partnerName}</p></div><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-extrabold text-indigo-700">{s.partnerSharePercent}% mitra</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><ShareLine label="Kas bersih PPN" value={s.cashRevenue}/><ShareLine label="HPP vendor" value={-s.vendorHpp}/><ShareLine label="Komisi reseller" value={-s.resellerCommission}/><ShareLine label="Operasional + refund" value={-(s.operatingExpense+s.refunds)}/></div><div className="mt-4 border-t border-slate-200 pt-3"><div className="flex justify-between text-xs"><span>Dasar bagi hasil</span><strong>{money(s.distributableProfit)}</strong></div><div className="mt-2 flex justify-between rounded-xl bg-indigo-600 p-3 text-white"><span className="text-xs font-bold">Hak mitra</span><strong>{money(s.partnerShareAmount)}</strong></div></div><button onClick={async()=>{await fetch('/api/profit-sharing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});setNotice(`Periode ${s.branchName} berhasil ditutup.`)}} className="mt-3 w-full rounded-lg border border-indigo-200 py-2 text-xs font-bold text-indigo-700 print:hidden">Tutup periode</button></div>)}{!shares.length&&<p className="col-span-2 p-8 text-center text-xs text-slate-400">Belum ada cabang kerja sama.</p>}</div></section>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 print:hidden"><form onSubmit={submit} className="w-full max-w-xl rounded-3xl bg-white p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-extrabold">Catat transaksi</h2><button type="button" onClick={()=>setOpen(false)}><X className="h-5 w-5"/></button></div><div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-bold">Cabang<select name="branchId" required className={`${field} mt-1`}>{payload.branches.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-xs font-bold">Tanggal<input name="transactionDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={`${field} mt-1`}/></label><label className="text-xs font-bold">Jenis<select name="direction" className={`${field} mt-1`}><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></label><label className="text-xs font-bold">Kategori<input name="category" required placeholder="Operasional cabang" className={`${field} mt-1`}/></label><label className="text-xs font-bold">Nilai<input name="amount" type="number" min="1" required className={`${field} mt-1`}/></label><label className="text-xs font-bold">Status<select name="status" className={`${field} mt-1`}><option value="approved">Disetujui</option><option value="pending">Menunggu persetujuan</option><option value="draft">Draft</option></select></label><label className="md:col-span-2 text-xs font-bold">Keterangan<textarea name="description" required className={`${field} mt-1`}/></label><label className="md:col-span-2 text-xs font-bold">Catatan<textarea name="notes" className={`${field} mt-1`}/></label></div><button className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">Simpan transaksi</button></form></div>}
 </div>
}
function Metric({icon:Icon,label,value,color}:{icon:any,label:string,value:string,color:string}){const cls:any={emerald:'bg-emerald-50 text-emerald-600',rose:'bg-rose-50 text-rose-600',blue:'bg-blue-50 text-blue-600',amber:'bg-amber-50 text-amber-600'};return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`inline-flex rounded-xl p-2 ${cls[color]}`}><Icon className="h-4 w-4"/></div><p className="mt-3 text-[10px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-lg font-extrabold">{value}</p></div>}
function ShareLine({label,value}:{label:string,value:number}){return <div className="rounded-lg bg-slate-50 p-2"><p className="text-[10px] text-slate-400">{label}</p><strong className={value<0?'text-rose-600':'text-slate-800'}>{value<0?'− ':''}{money(Math.abs(value))}</strong></div>}
