'use client';

import { useEffect, useState } from 'react';
import { Building2, Handshake, Plus, Store, Users, X } from 'lucide-react';

const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500';
const labels:any={property:'Properti',reseller:'Agent / Reseller',vendor:'Vendor'};

export default function PartnersPage(){
  const [partners,setPartners]=useState<any[]>([]);const [filter,setFilter]=useState('all');const [open,setOpen]=useState(false);const [notice,setNotice]=useState('');
  const [invitePartner,setInvitePartner]=useState<any>(null);const [inviteResult,setInviteResult]=useState<any>(null);
  const load=async()=>{const out=await fetch('/api/partners').then(r=>r.json());setPartners(out.data||[])};useEffect(()=>{load()},[]);
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const raw:any=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch('/api/partners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...raw,code:String(raw.code).toUpperCase(),commissionDefaultRate:raw.commissionDefaultRate?Number(raw.commissionDefaultRate):undefined,isActive:true})});const out=await res.json();if(!res.ok){setNotice(out.error);return}setOpen(false);setNotice('Mitra berhasil ditambahkan.');load()};
  const shown=filter==='all'?partners:partners.filter(p=>p.partnerType===filter);
  const invite=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...raw,role:invitePartner.partnerType==='property'?'property_partner':'reseller',partnerId:invitePartner.id,fullName:invitePartner.contactName||invitePartner.name,email:invitePartner.email,phone:invitePartner.phone})});const out=await res.json();setInviteResult(out.data||{error:out.error});if(out.success)load()};
  return <div className="space-y-6"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-600">Ekosistem BOffice</p><h1 className="mt-1 text-2xl font-extrabold">Manajemen Mitra</h1><p className="mt-1 text-sm text-slate-500">Properti, reseller, vendor, dan akses portal dalam satu direktori.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Tambah mitra</button></div>
  {notice&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{notice}</div>}
  <div className="grid gap-4 md:grid-cols-3"><Card icon={Building2} label="Mitra properti" value={partners.filter(p=>p.partnerType==='property').length}/><Card icon={Users} label="Reseller" value={partners.filter(p=>p.partnerType==='reseller').length}/><Card icon={Store} label="Vendor" value={partners.filter(p=>p.partnerType==='vendor').length}/></div>
  <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b border-slate-100 p-4">{['all','property','reseller','vendor'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-lg px-3 py-2 text-xs font-bold ${filter===x?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{x==='all'?'Semua':labels[x]}</button>)}</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-5 py-3">Mitra</th><th className="px-5 py-3">Jenis</th><th className="px-5 py-3">Kontak</th><th className="px-5 py-3">Skema default</th><th className="px-5 py-3">Akses</th></tr></thead><tbody className="divide-y divide-slate-100">{shown.map(p=><tr key={p.id}><td className="px-5 py-4"><strong className="text-slate-900">{p.name}</strong><p className="font-mono text-[10px] text-slate-400">{p.code}</p></td><td className="px-5 py-4"><span className="rounded-full bg-indigo-50 px-2.5 py-1 font-bold text-indigo-700">{labels[p.partnerType]}</span></td><td className="px-5 py-4"><p>{p.contactName||'-'}</p><p className="text-slate-500">{p.phone||p.email||'-'}</p></td><td className="px-5 py-4">{p.partnerType==='reseller'?(p.commissionDefaultModel==='percentage'?`${p.commissionDefaultRate||0}%`:'Markup harga'):'—'}</td><td className="px-5 py-4">{p.partnerType==='vendor'?<span className="text-slate-400">Tidak perlu portal</span>:p.userId?<span className="font-bold text-emerald-600">Portal aktif</span>:<button onClick={()=>{setInvitePartner(p);setInviteResult(null)}} className="rounded-lg border border-indigo-200 px-2.5 py-1.5 font-bold text-indigo-700">Kirim undangan</button>}</td></tr>)}</tbody></table></div></div>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-2xl rounded-3xl bg-white p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-extrabold">Tambah mitra</h2><button type="button" onClick={()=>setOpen(false)}><X className="h-5 w-5"/></button></div><div className="grid gap-4 md:grid-cols-2"><Input name="code" label="Kode mitra" required/><Input name="name" label="Nama mitra" required/><label className="text-xs font-bold">Jenis mitra<select name="partnerType" className={`${field} mt-1`}><option value="property">Properti</option><option value="reseller">Agent / Reseller</option><option value="vendor">Vendor</option></select></label><Input name="contactName" label="Nama kontak"/><Input name="phone" label="WhatsApp"/><Input name="email" label="Email" type="email"/><label className="text-xs font-bold">Skema komisi default<select name="commissionDefaultModel" className={`${field} mt-1`}><option value="">Tidak ada</option><option value="percentage">Persentase</option><option value="markup">Markup harga</option></select></label><Input name="commissionDefaultRate" label="Persentase default" type="number"/><label className="md:col-span-2 text-xs font-bold">Alamat<textarea name="address" className={`${field} mt-1`}/></label><label className="md:col-span-2 text-xs font-bold">Catatan<textarea name="notes" className={`${field} mt-1`}/></label></div><button className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">Simpan mitra</button></form></div>}
  {invitePartner&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={invite} className="w-full max-w-md rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h2 className="font-extrabold">Undang ke portal</h2><p className="text-xs text-slate-500">{invitePartner.name}</p></div><button type="button" onClick={()=>setInvitePartner(null)}><X className="h-5 w-5"/></button></div><label className="mt-5 block text-xs font-bold">Kirim melalui<select name="channel" className={`${field} mt-1`}><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="link">Buat tautan saja</option></select></label>{inviteResult&&<div className="mt-4 rounded-xl bg-blue-50 p-3 text-xs text-blue-800">{inviteResult.error||<input readOnly value={inviteResult.inviteUrl} className="w-full rounded-lg border p-2"/>}</div>}<button disabled={!invitePartner.email} className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-40">Buat undangan</button></form></div>}
  </div>
}
function Card({icon:Icon,label,value}:{icon:any,label:string,value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><Icon className="h-4 w-4 text-indigo-600"/>{label}</div><p className="mt-2 text-3xl font-extrabold">{value}</p></div>}
function Input({label,...props}:any){return <label className="text-xs font-bold">{label}<input {...props} className={`${field} mt-1`}/></label>}
